In [80]:
import numpy as np
import pandas as pd

In [81]:
df = pd.read_csv(r'Datasets\Titanic-Dataset.csv')

In [82]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [83]:
df.shape

(891, 12)

In [84]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [86]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [87]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [88]:
df.drop(columns = ['Cabin'], inplace = True) # Too many missing values

In [89]:
# Dropping Unnecessary Columns
df.drop(columns=['PassengerId', 'Name', 'Ticket'], inplace=True)

In [90]:
df['Sex'].unique() # Contains Categorical Values

array(['male', 'female'], dtype=object)

In [91]:
df['Sex'] = df['Sex'].map({'male' : 0, 'female' : 1})

In [92]:
df['Sex'].unique() # Now Numerical Values

array([0, 1])

In [93]:
df['Embarked'].unique()

array(['S', 'C', 'Q'], dtype=object)

In [94]:
df['Embarked'] = df['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

In [96]:
df['Embarked'].unique()

array([0, 1, 2])

#### Feature Engineering

In [97]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0
3         1       1    1  35.0      1      0  53.1000         0
4         0       3    0  35.0      0      0   8.0500         0

In [99]:
# SibSp -> Number of siblings + spouses traveling with the passenger.
# Parch -> Number of parents + children traveling with the passenger.
# We can combine these two columns as FamilySize
df['Family Size'] = df['SibSp'] + df['Parch']

In [100]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Family Size
0         0       3    0  22.0      1      0   7.2500         0            1
1         1       1    1  38.0      1      0  71.2833         1            1
2         1       3    1  26.0      0      0   7.9250         0            0
3         1       1    1  35.0      1      0  53.1000         0            1
4         0       3    0  35.0      0      0   8.0500         0            0

In [102]:
df['IsAlone'] = np.where(df['Family Size'] == 0, 1, 0)

In [103]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Family Size,IsAlone
0,0,3,0,22.0,1,0,7.2500,0,1,0
1,1,1,1,38.0,1,0,71.2833,1,1,0
2,1,3,1,26.0,0,0,7.9250,0,0,1
3,1,1,1,35.0,1,0,53.1000,0,1,0
4,0,3,0,35.0,0,0,8.0500,0,0,1

In [104]:
df.to_csv('Data_Cleaning.csv', index = False)